---
- name: Setup Caddy with reverse proxy
  hosts: all
  become: yes
  tasks:
    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        state: present
        update_cache: yes

    - name: Create Caddyfile
      ansible.builtin.copy:
        content: |
          coach.dimalip.in {
            reverse_proxy localhost:8080
          }
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Caddy service is running and enabled
      ansible.builtin.systemd:
        name: caddy
        state: restarted
        enabled: yes
