---
- name: Setup Caddy with reverse proxy
  hosts: all
  become: yes
  tasks:

    - name: Create Caddyfile
      ansible.builtin.copy:
        content: |
          coach.dimalip.in {
            @admin path /admin*

            handle @admin {
              forward_auth localhost:4180 {
                uri /oauth2/auth
                copy_headers Authorization X-Auth-User Set-Cookie
                header_up X-Real-IP {remote_host}
                header_up X-Forwarded-Uri {uri}

                @error status 401
                handle_response @error {
                  redir https://coach.dimalip.in/oauth2/sign_in?rd={uri}
                }
              }
              reverse_proxy localhost:8080
            }

            handle /oauth2/* {
              reverse_proxy localhost:4180
            }

            handle {
              reverse_proxy localhost:8080
            }
          }
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: '0644'
