---
- name: Setup Caddy with reverse proxy
  hosts: all
  become: yes
  tasks:

    - name: Create Caddyfile
      ansible.builtin.copy:
        content: |
          coach.dimalip.in {
            reverse_proxy localhost:8080
          }
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: '0644'
